In [37]:
# import required modules
import GEOparse
import os
import gzip
import csv
import re
import pandas as pd

#### Experiment the series dataset

In [38]:
# create a GEOparse object
gse = GEOparse.get_GEO(filepath="../data_gene/GSE39540_family.soft.gz")

19-Mar-2025 12:53:49 INFO GEOparse - Parsing ../data_gene/GSE39540_family.soft.gz:
19-Mar-2025 12:53:49 DEBUG GEOparse - DATABASE: GeoMiame
19-Mar-2025 12:53:49 DEBUG GEOparse - SERIES: GSE39540
19-Mar-2025 12:53:49 DEBUG GEOparse - PLATFORM: GPL571
19-Mar-2025 12:53:49 DEBUG GEOparse - SAMPLE: GSM971351
19-Mar-2025 12:53:49 DEBUG GEOparse - SAMPLE: GSM971352
19-Mar-2025 12:53:49 DEBUG GEOparse - SAMPLE: GSM971353
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971354
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971355
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971356
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971357
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971358
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971359
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971360
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971361
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971362
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971363
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971364
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971365
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971366
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971367
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971368
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971369
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971370
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971371
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971372
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971373
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971374
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971375
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971376
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971377
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971378
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971379
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971380
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971381
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971382
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971383
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971384
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971385
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971386
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971387
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971388
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971389
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971390
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971391
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971392
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971393
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971394
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971395
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971396
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971397
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971398
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971399
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971400
19-Mar-2025 12:53:50 DEBUG GEOparse - SAMPLE: GSM971401
19-Mar-2025 12:53:51 DEBUG GEOparse - SAMPLE: GSM971402
19-Mar-2025 12:53:51 DEBUG GEOparse - SAMPLE: GSM971403
19-Mar-2025 12:53:51 DEBUG GEOparse - SAMPLE: GSM971404
19-Mar-2025 12:53:51 DEBUG GEOparse - SAMPLE: GSM971405
19-Mar-2025 12:53:51 DEBUG GEOparse - SAMPLE: GSM971406
19-Mar-2025 12:53:51 DEBUG GEOparse - SAMPLE: GSM971407
19-Mar-2025 12:53:51 DEBUG GEOparse - SAMPLE: GSM971408
19-Mar-2025 12:53:51 DEBUG GEOparse - SAMPLE: GSM971409
19-Mar-2025 12:53:51 DEBUG GEOparse - SAMPLE: GSM971410
19-Mar-2025 12:53:51 DEBUG GEOparse - SAMPLE: GSM971411

In [39]:
# print the metadata
print(gse.metadata)

{'title': ['A mesenchymal stromal cell gene signature for donor age'], 'geo_accession': ['GSE39540'], 'status': ['Public on Jul 21 2012'], 'submission_date': ['Jul 20 2012'], 'last_update_date': ['Dec 06 2018'], 'pubmed_id': ['22927939'], 'summary': ['Human aging is associated with loss of function and regenerative capacity. Human bone marrow derived mesenchymal stromal cells (hMSCs) are involved in tissue regeneration, evidenced by their capacity to differentiate into several lineages and therefore are considered the gold standard for cell-based regeneration therapy. Tissue maintenance and regeneration is dependent on stem cells and declines with age and aging is thought to influence therapeutic efficacy, therefore, more insight in the process of aging of hMSCs is of high interest. We, therefore, hypothesized that hMSCs might reflect signs of aging. In order to find markers for donor age, early passage hMSCs were isolated from bone marrow of 61 donors, with ages varying from 17-84, and clinical parameters, in vitro characteristics and microarray analysis were assessed. Although clinical parameters and in vitro performance did not yield reliable markers for aging since large donor variations were present, genome-wide microarray analysis resulted in a considerable list of genes correlating with human age. By comparing the transcriptional profile of aging in human with the one from rat, we discovered follistatin as a common marker for aging in both species. The gene signature presented here could be a useful tool for drug testing to rejuvenate hMSCs or for the selection of more potent, hMSCs for cell-based therapy.', 'We used microaray gene expression profiling to find expressed genes that correlated with the donor age of bone-marrow derived mesenchymal stromal cells (hMSCs)'], 'overall_design': ['Human mesenchymal stem cells (hMSC) were biopsied from bone marrow from 61 different donors aging from 17 - 89 years old. The genome wide expression profiles was assessed using Affymetrix microarrays. The expression of genes was correlated with the age of the donors.'], 'type': ['Expression profiling by array'], 'contributor': ['Hugo,,Alves', 'Jetty,,van Ginkel', 'Nathalie,,Groen', 'Marc,,Hulsman', 'Anouk,,Mentink', 'Marcel,,Reinders', 'Clemens,,van Blitterswijk', 'Jan,,de Boer'], 'sample_id': ['GSM971351', 'GSM971352', 'GSM971353', 'GSM971354', 'GSM971355', 'GSM971356', 'GSM971357', 'GSM971358', 'GSM971359', 'GSM971360', 'GSM971361', 'GSM971362', 'GSM971363', 'GSM971364', 'GSM971365', 'GSM971366', 'GSM971367', 'GSM971368', 'GSM971369', 'GSM971370', 'GSM971371', 'GSM971372', 'GSM971373', 'GSM971374', 'GSM971375', 'GSM971376', 'GSM971377', 'GSM971378', 'GSM971379', 'GSM971380', 'GSM971381', 'GSM971382', 'GSM971383', 'GSM971384', 'GSM971385', 'GSM971386', 'GSM971387', 'GSM971388', 'GSM971389', 'GSM971390', 'GSM971391', 'GSM971392', 'GSM971393', 'GSM971394', 'GSM971395', 'GSM971396', 'GSM971397', 'GSM971398', 'GSM971399', 'GSM971400', 'GSM971401', 'GSM971402', 'GSM971403', 'GSM971404', 'GSM971405', 'GSM971406', 'GSM971407', 'GSM971408', 'GSM971409', 'GSM971410', 'GSM971411'], 'contact_name': ['Nathalie,,Groen'], 'contact_email': ['n.groen@utwente.nl'], 'contact_phone': ['0031534893062'], 'contact_department': ['Tissue Regeration'], 'contact_institute': ['University of Twente - MIRA – Institute for Biomedical Technology and Technical Medicine'], 'contact_address': ['Drienerlolaan 5'], 'contact_city': ['Enschede'], 'contact_zip/postal_code': ['7522 NB'], 'contact_country': ['Netherlands'], 'supplementary_file': ['ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE39nnn/GSE39540/suppl/GSE39540_RAW.tar'], 'platform_id': ['GPL571'], 'platform_taxid': ['9606'], 'sample_taxid': ['9606'], 'relation': ['BioProject: https://www.ncbi.nlm.nih.gov/bioproject/PRJNA171065']}

In [40]:
{
    "title": ["A mesenchymal stromal cell gene signature for donor age"],
    "geo_accession": ["GSE39540"],
    "status": ["Public on Jul 21 2012"],
    "submission_date": ["Jul 20 2012"],
    "last_update_date": ["Dec 06 2018"],
    "pubmed_id": ["22927939"],
    "summary": [
        "Human aging is associated with loss of function and regenerative capacity. Human bone marrow derived mesenchymal stromal cells (hMSCs) are involved in tissue regeneration, evidenced by their capacity to differentiate into several lineages and therefore are considered the gold standard for cell-based regeneration therapy. Tissue maintenance and regeneration is dependent on stem cells and declines with age and aging is thought to influence therapeutic efficacy, therefore, more insight in the process of aging of hMSCs is of high interest. We, therefore, hypothesized that hMSCs might reflect signs of aging. In order to find markers for donor age, early passage hMSCs were isolated from bone marrow of 61 donors, with ages varying from 17-84, and clinical parameters, in vitro characteristics and microarray analysis were assessed. Although clinical parameters and in vitro performance did not yield reliable markers for aging since large donor variations were present, genome-wide microarray analysis resulted in a considerable list of genes correlating with human age. By comparing the transcriptional profile of aging in human with the one from rat, we discovered follistatin as a common marker for aging in both species. The gene signature presented here could be a useful tool for drug testing to rejuvenate hMSCs or for the selection of more potent, hMSCs for cell-based therapy.",
        "We used microaray gene expression profiling to find expressed genes that correlated with the donor age of bone-marrow derived mesenchymal stromal cells (hMSCs)",
    ],
    "overall_design": [
        "Human mesenchymal stem cells (hMSC) were biopsied from bone marrow from 61 different donors aging from 17 - 89 years old. The genome wide expression profiles was assessed using Affymetrix microarrays. The expression of genes was correlated with the age of the donors."
    ],
    "type": ["Expression profiling by array"],
    "contributor": [
        "Hugo,,Alves",
        "Jetty,,van Ginkel",
        "Nathalie,,Groen",
        "Marc,,Hulsman",
        "Anouk,,Mentink",
        "Marcel,,Reinders",
        "Clemens,,van Blitterswijk",
        "Jan,,de Boer",
    ],
    "sample_id": [
        "GSM971351",
        "GSM971352",
        "GSM971353",
        "GSM971354",
        "GSM971355",
        "GSM971356",
        "GSM971357",
        "GSM971358",
        "GSM971359",
        "GSM971360",
        "GSM971361",
        "GSM971362",
        "GSM971363",
        "GSM971364",
        "GSM971365",
        "GSM971366",
        "GSM971367",
        "GSM971368",
        "GSM971369",
        "GSM971370",
        "GSM971371",
        "GSM971372",
        "GSM971373",
        "GSM971374",
        "GSM971375",
        "GSM971376",
        "GSM971377",
        "GSM971378",
        "GSM971379",
        "GSM971380",
        "GSM971381",
        "GSM971382",
        "GSM971383",
        "GSM971384",
        "GSM971385",
        "GSM971386",
        "GSM971387",
        "GSM971388",
        "GSM971389",
        "GSM971390",
        "GSM971391",
        "GSM971392",
        "GSM971393",
        "GSM971394",
        "GSM971395",
        "GSM971396",
        "GSM971397",
        "GSM971398",
        "GSM971399",
        "GSM971400",
        "GSM971401",
        "GSM971402",
        "GSM971403",
        "GSM971404",
        "GSM971405",
        "GSM971406",
        "GSM971407",
        "GSM971408",
        "GSM971409",
        "GSM971410",
        "GSM971411",
    ],
    "contact_name": ["Nathalie,,Groen"],
    "contact_email": ["n.groen@utwente.nl"],
    "contact_phone": ["0031534893062"],
    "contact_department": ["Tissue Regeration"],
    "contact_institute": [
        "University of Twente - MIRA – Institute for Biomedical Technology and Technical Medicine"
    ],
    "contact_address": ["Drienerlolaan 5"],
    "contact_city": ["Enschede"],
    "contact_zip/postal_code": ["7522 NB"],
    "contact_country": ["Netherlands"],
    "supplementary_file": [
        "ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE39nnn/GSE39540/suppl/GSE39540_RAW.tar"
    ],
    "platform_id": ["GPL571"],
    "platform_taxid": ["9606"],
    "sample_taxid": ["9606"],
    "relation": ["BioProject: https://www.ncbi.nlm.nih.gov/bioproject/PRJNA171065"],
}

{'title': ['A mesenchymal stromal cell gene signature for donor age'],
 'geo_accession': ['GSE39540'],
 'status': ['Public on Jul 21 2012'],
 'submission_date': ['Jul 20 2012'],
 'last_update_date': ['Dec 06 2018'],
 'pubmed_id': ['22927939'],
 'summary': ['Human aging is associated with loss of function and regenerative capacity. Human bone marrow derived mesenchymal stromal cells (hMSCs) are involved in tissue regeneration, evidenced by their capacity to differentiate into several lineages and therefore are considered the gold standard for cell-based regeneration therapy. Tissue maintenance and regeneration is dependent on stem cells and declines with age and aging is thought to influence therapeutic efficacy, therefore, more insight in the process of aging of hMSCs is of high interest. We, therefore, hypothesized that hMSCs might reflect signs of aging. In order to find markers for donor age, early passage hMSCs were isolated from bone marrow of 61 donors, with ages varying from 17-84, and clinical parameters, in vitro characteristics and microarray analysis were assessed. Although clinical parameters and in vitro performance did not yield reliable markers for aging since large donor variations were present, genome-wide microarray analysis resulted in a considerable list of genes correlating with human age. By comparing the transcriptional profile of aging in human with the one from rat, we discovered follistatin as a common marker for aging in both species. The gene signature presented here could be a useful tool for drug testing to rejuvenate hMSCs or for the selection of more potent, hMSCs for cell-based therapy.',
  'We used microaray gene expression profiling to find expressed genes that correlated with the donor age of bone-marrow derived mesenchymal stromal cells (hMSCs)'],
 'overall_design': ['Human mesenchymal stem cells (hMSC) were biopsied from bone marrow from 61 different donors aging from 17 - 89 years old. The genome wide expression profiles was assessed using Affymetrix microarrays. The expression of genes was correlated with the age of the donors.'],
 'type': ['Expression profiling by array'],
 'contributor': ['Hugo,,Alves',
  'Jetty,,van Ginkel',
  'Nathalie,,Groen',
  'Marc,,Hulsman',
  'Anouk,,Mentink',
  'Marcel,,Reinders',
  'Clemens,,van Blitterswijk',
  'Jan,,de Boer'],
 'sample_id': ['GSM971351',
  'GSM971352',
  'GSM971353',
  'GSM971354',
  'GSM971355',
  'GSM971356',
  'GSM971357',
  'GSM971358',
  'GSM971359',
  'GSM971360',
  'GSM971361',
  'GSM971362',
  'GSM971363',
  'GSM971364',
  'GSM971365',
  'GSM971366',
  'GSM971367',
  'GSM971368',
  'GSM971369',
  'GSM971370',
  'GSM971371',
  'GSM971372',
  'GSM971373',
  'GSM971374',
  'GSM971375',
  'GSM971376',
  'GSM971377',
  'GSM971378',
  'GSM971379',
  'GSM971380',
  'GSM971381',
  'GSM971382',
  'GSM971383',
  'GSM971384',
  'GSM971385',
  'GSM971386',
  'GSM971387',
  'GSM971388',
  'GSM971389',
  'GSM971390',
  'GSM971391',
  'GSM971392',
  'GSM971393',
  'GSM971394',
  'GSM971395',
  'GSM971396',
  'GSM971397',
  'GSM971398',
  'GSM971399',
  'GSM971400',
  'GSM971401',
  'GSM971402',
  'GSM971403',
  'GSM971404',
  'GSM971405',
  'GSM971406',
  'GSM971407',
  'GSM971408',
  'GSM971409',
  'GSM971410',
  'GSM971411'],
 'contact_name': ['Nathalie,,Groen'],
 'contact_email': ['n.groen@utwente.nl'],
 'contact_phone': ['0031534893062'],
 'contact_department': ['Tissue Regeration'],
 'contact_institute': ['University of Twente - MIRA – Institute for Biomedical Technology and Technical Medicine'],
 'contact_address': ['Drienerlolaan 5'],
 'contact_city': ['Enschede'],
 'contact_zip/postal_code': ['7522 NB'],
 'contact_country': ['Netherlands'],
 'supplementary_file': ['ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE39nnn/GSE39540/suppl/GSE39540_RAW.tar'],
 'platform_id': ['GPL571'],
 'platform_taxid': ['9606'],
 'sample_taxid': ['9606'],
 'relation': ['BioProject: https://www.ncbi.nlm.nih.gov/bioproject/PRJNA171065']}

In [41]:
# Display the platforms in the dataset
gse.gpls["GPL571"].columns

                                                                        description
ID                                Affymetrix Probe Set ID LINK_PRE:"https://www....
GB_ACC                            GenBank Accession Number LINK_PRE:"http://www....
SPOT_ID                                                         identifies controls
Species Scientific Name           The genus and species of the organism represen...
Annotation Date                   The date that the annotations for this probe a...
Sequence Type
Sequence Source                   The database from which the sequence used to d...
Target Description
Representative Public ID          The accession number of a representative seque...
Gene Title                              Title of Gene represented by the probe set.
Gene Symbol                       A gene symbol, when one is available (from Uni...
ENTREZ_GENE_ID                    Entrez Gene Database UID LINK_PRE:"http://www....
RefSeq Transcript ID              References to multiple sequences in RefSeq. Th...
Gene Ontology Biological Process  Gene Ontology Consortium Biological Process de...
Gene Ontology Cellular Component  Gene Ontology Consortium Cellular Component de...
Gene Ontology Molecular Function  Gene Ontology Consortium Molecular Function de...

In [42]:

class PubMedDataExtractor:
    def __init__(self, data_dir, geo_output_file, sample_output_file):
        self.data_dir = data_dir
        self.geo_output_file = geo_output_file
        self.sample_output_file = sample_output_file

    def extract_geo_data(self, file_path):
        """Extracts PubMed ID and GEO Accession from a .soft.gz file."""
        pubmed_id = None
        geo_accession = None
        
        try:
            with gzip.open(file_path, "rt", encoding="utf-8") as f:
                for line in f:
                    if line.startswith("^SERIES = GSE"):
                        geo_accession = line.strip().split(" = ")[1]
                    elif line.startswith("!Series_pubmed_id ="):
                        pubmed_id = line.strip().split(" = ")[1]
                    
                    if pubmed_id and geo_accession:
                        break
        except Exception as e:
            print(f"Error processing {file_path}: {e}")

        return pubmed_id if pubmed_id else "null", geo_accession

    def extract_sample_data(self, file_path):
        """Extracts PubMed ID and Reference Series from a .soft.gz file."""
        pubmed_id = None
        reference_series = None
        
        try:
            with gzip.open(file_path, "rt", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if line.startswith("!dataset_reference_series = GSE"):
                        reference_series = line.split(" = ")[-1]
                    elif line.startswith("!dataset_pubmed_id ="):
                        pubmed_id = line.split(" = ")[-1]
                    if pubmed_id and reference_series:
                        break
        except Exception as e:
            print(f"Error processing {file_path}: {e}")

        return pubmed_id if pubmed_id else "null", reference_series if reference_series else "null"

    def process_geo_directory(self):
        """Processes .soft.gz files for GEO Accession data and saves to CSV."""
        with open(self.geo_output_file, mode="w", newline="") as file:
            writer = csv.writer(file)
            writer.writerow(["File Name", "GEO Accession", "PubMed ID"])

            for filename in os.listdir(self.data_dir):
                if filename.endswith("_family.soft.gz"):
                    file_path = os.path.join(self.data_dir, filename)
                    pubmed_id, geo_accession = self.extract_geo_data(file_path)
                    
                    if pubmed_id or geo_accession:
                        writer.writerow([filename, geo_accession, pubmed_id])
                        print(f"Processed {filename}: GEO Accession: {geo_accession}, PubMed ID: {pubmed_id}")
        
        print(f"\nData saved to {self.geo_output_file}")

    def process_sample_directory(self):
        """Processes .soft.gz files for Sample data and saves to CSV."""
        with open(self.sample_output_file, mode="w", newline="") as file:
            writer = csv.writer(file)
            writer.writerow(["File Name", "Reference Series", "PubMed ID"])

            for filename in os.listdir(self.data_dir):
                if filename.startswith("GDS"):
                    file_path = os.path.join(self.data_dir, filename)
                    pubmed_id, reference_series = self.extract_sample_data(file_path)
                    if pubmed_id != "null" or reference_series != "null":
                        writer.writerow([filename, reference_series, pubmed_id])
                        print(f"Processed: {filename}: Reference Series: {reference_series}, PubMed ID: {pubmed_id}")
        
        print(f"\nData saved to {self.sample_output_file}")

if __name__ == "__main__":
    DATA_DIR = "../data_gene/"
    OUTPUT_FILE_GEO = "../data/pubmed_geo_data.csv"
    OUTPUT_FILE_SAMPLE = "../data/pubmed_sample_data.csv"
    extractor = PubMedDataExtractor(DATA_DIR, OUTPUT_FILE_GEO, OUTPUT_FILE_SAMPLE)
    extractor.process_geo_directory()

Processed GSE56580_family.soft.gz: GEO Accession: GSE56580, PubMed ID: 25404168
Processed GSE58137_family.soft.gz: GEO Accession: GSE58137, PubMed ID: null
Processed GSE5086_family.soft.gz: GEO Accession: GSE5086, PubMed ID: 16789832
Processed GSE63060_family.soft.gz: GEO Accession: GSE63060, PubMed ID: 26343147
Processed GSE21681_family.soft.gz: GEO Accession: GSE21681, PubMed ID: 21055414
Processed GSE35322_family.soft.gz: GEO Accession: GSE35322, PubMed ID: 22413003
Processed GSE7958_family.soft.gz: GEO Accession: GSE7958, PubMed ID: 17519223
Processed GSE11291_family.soft.gz: GEO Accession: GSE11291, PubMed ID: 18523577
Processed GSE39540_family.soft.gz: GEO Accession: GSE39540, PubMed ID: 22927939
Processed GSE66857_family.soft.gz: GEO Accession: GSE66857, PubMed ID: 26484237
Processed GSE36192_family.soft.gz: GEO Accession: GSE36192, PubMed ID: 22433082
Processed GSE73450_family.soft.gz: GEO Accession: GSE73450, PubMed ID: 26497558
Processed GSE12277_family.soft.gz: GEO Accession: GSE12277, PubMed ID: 19513108
Processed GSE34378_family.soft.gz: GEO Accession: GSE34378, PubMed ID: 23795901
Processed GSE69187_family.soft.gz: GEO Accession: GSE69187, PubMed ID: 27135421
Processed GSE40645_family.soft.gz: GEO Accession: GSE40645, PubMed ID: 24524210
Processed GSE56045_family.soft.gz: GEO Accession: GSE56045, PubMed ID: 25404168
Processed GSE32719_family.soft.gz: GEO Accession: GSE32719, PubMed ID: 22123971
Processed GSE61915_family.soft.gz: GEO Accession: GSE61915, PubMed ID: 25431548
Processed GSE19676_family.soft.gz: GEO Accession: GSE19676, PubMed ID: 20089533
Processed GSE48911_family.soft.gz: GEO Accession: GSE48911, PubMed ID: 24593767
Processed GSE12480_family.soft.gz: GEO Accession: GSE12480, PubMed ID: null
Processed GSE27625_family.soft.gz: GEO Accession: GSE27625, PubMed ID: 22049228
Processed GSE74463_family.soft.gz: GEO Accession: GSE74463, PubMed ID: null
Processed GSE69832_family.soft.gz: GEO Accession: GSE69832, PubMed ID: 26362218
Processed GSE11097_family.soft.gz: GEO Accession: GSE11097, PubMed ID: 18653662
Processed GSE16487_family.soft.gz: GEO Accession: GSE16487, PubMed ID: 21108734

Data saved to ../data/pubmed_geo_data.csv

In [43]:
df = pd.read_csv("../data/pubmed_geo_data.csv")
df

                  File Name GEO Accession   PubMed ID
0   GSE56580_family.soft.gz      GSE56580  25404168.0
1   GSE58137_family.soft.gz      GSE58137         NaN
2    GSE5086_family.soft.gz       GSE5086  16789832.0
3   GSE63060_family.soft.gz      GSE63060  26343147.0
4   GSE21681_family.soft.gz      GSE21681  21055414.0
5   GSE35322_family.soft.gz      GSE35322  22413003.0
6    GSE7958_family.soft.gz       GSE7958  17519223.0
7   GSE11291_family.soft.gz      GSE11291  18523577.0
8   GSE39540_family.soft.gz      GSE39540  22927939.0
9   GSE66857_family.soft.gz      GSE66857  26484237.0
10  GSE36192_family.soft.gz      GSE36192  22433082.0
11  GSE73450_family.soft.gz      GSE73450  26497558.0
12  GSE12277_family.soft.gz      GSE12277  19513108.0
13  GSE34378_family.soft.gz      GSE34378  23795901.0
14  GSE69187_family.soft.gz      GSE69187  27135421.0
15  GSE40645_family.soft.gz      GSE40645  24524210.0
16  GSE56045_family.soft.gz      GSE56045  25404168.0
17  GSE32719_family.soft.gz      GSE32719  22123971.0
18  GSE61915_family.soft.gz      GSE61915  25431548.0
19  GSE19676_family.soft.gz      GSE19676  20089533.0
20  GSE48911_family.soft.gz      GSE48911  24593767.0
21  GSE12480_family.soft.gz      GSE12480         NaN
22  GSE27625_family.soft.gz      GSE27625  22049228.0
23  GSE74463_family.soft.gz      GSE74463         NaN
24  GSE69832_family.soft.gz      GSE69832  26362218.0
25  GSE11097_family.soft.gz      GSE11097  18653662.0
26  GSE16487_family.soft.gz      GSE16487  21108734.0

In [44]:
df.shape

(27, 3)

#### Experiment the sample dataset

In [45]:
# create a GEOparse object
gds = GEOparse.get_GEO(filepath="../data_gene/GDS3939.soft.gz", geotype="GDS")

19-Mar-2025 12:53:54 INFO GEOparse - Parsing ../data_gene/GDS3939.soft.gz:
19-Mar-2025 12:53:54 DEBUG GEOparse - DATABASE: Geo
19-Mar-2025 12:53:54 DEBUG GEOparse - DATASET: GDS3939
19-Mar-2025 12:53:54 DEBUG GEOparse - SUBSET: GDS3939_1
19-Mar-2025 12:53:54 DEBUG GEOparse - SUBSET: GDS3939_2
19-Mar-2025 12:53:54 DEBUG GEOparse - SUBSET: GDS3939_3
19-Mar-2025 12:53:54 DEBUG GEOparse - SUBSET: GDS3939_4
19-Mar-2025 12:53:54 DEBUG GEOparse - SUBSET: GDS3939_5
19-Mar-2025 12:53:54 DEBUG GEOparse - SUBSET: GDS3939_6
19-Mar-2025 12:53:54 DEBUG GEOparse - SUBSET: GDS3939_7
19-Mar-2025 12:53:54 DEBUG GEOparse - SUBSET: GDS3939_8
19-Mar-2025 12:53:54 DEBUG GEOparse - DATASET: GDS3939

In [46]:
# print the metadata
print("Available metadata keys:", gds.metadata.keys())

Available metadata keys: dict_keys(['title', 'description', 'type', 'pubmed_id', 'platform', 'platform_organism', 'platform_technology_type', 'feature_count', 'sample_organism', 'sample_type', 'channel_count', 'sample_count', 'value_type', 'reference_series', 'order', 'update_date'])

In [47]:
(
    [
        "title",
        "description",
        "type",
        "pubmed_id",
        "platform",
        "platform_organism",
        "platform_technology_type",
        "feature_count",
        "sample_organism",
        "sample_type",
        "channel_count",
        "sample_count",
        "value_type",
        "reference_series",
        "order",
        "update_date",
    ]
)

['title',
 'description',
 'type',
 'pubmed_id',
 'platform',
 'platform_organism',
 'platform_technology_type',
 'feature_count',
 'sample_organism',
 'sample_type',
 'channel_count',
 'sample_count',
 'value_type',
 'reference_series',
 'order',
 'update_date']

In [48]:
# metadata
gds.metadata

{'title': ['Fisher 344 rat model of aging: parietal cortex'],
 'description': ['Analysis of parietal cortices of young and aged F344 males implanted with telemetry devices to measure sleep architecture. Animals were trained in the Morris water maze to assess cognitive function. Results provide insight into possible mechanistic links between sleep changes and cognitive aging.'],
 'type': ['Expression profiling by array'],
 'pubmed_id': ['21483696'],
 'platform': ['GPL1355'],
 'platform_organism': ['Rattus norvegicus'],
 'platform_technology_type': ['in situ oligonucleotide'],
 'feature_count': ['31099'],
 'sample_organism': ['Rattus norvegicus'],
 'sample_type': ['RNA'],
 'channel_count': ['1'],
 'sample_count': ['12'],
 'value_type': ['count'],
 'reference_series': ['GSE24515'],
 'order': ['none'],
 'update_date': ['Dec 20 2011']}

In [49]:
# Display table data
gds.table.head(10)

,ID_REF,IDENTIFIER,GSM604547,GSM604548,GSM604549,GSM604550,GSM604551,GSM604552,GSM604553,GSM604554,GSM604555,GSM604556,GSM604557,GSM604558
0,1367452_at,Sumo2,5363.100,5365.360,5805.77,5075.820,5778.06,5694.130,4814.170,5653.550,5412.19,5443.880,5727.620,5160.400
1,1367453_at,Cdc37,3180.450,2913.840,3299.54,2897.340,2849.75,2665.250,3115.390,3261.620,3125.95,3354.340,2853.160,2554.740
2,1367454_at,Copb2,1959.640,1869.790,1823.44,1950.740,1761.30,1697.820,1635.700,1857.520,1828.27,1780.210,1658.890,1592.210
3,1367455_at,Vcp,4200.290,4251.240,4513.55,4280.200,4364.13,4709.520,4450.130,4486.010,3984.17,4028.510,4159.120,3906.550
4,1367456_at,Ube2d2,4611.140,4480.420,4508.46,4485.520,4114.78,4730.770,4231.960,4231.340,4197.21,4476.040,4178.020,3602.580
5,1367457_at,Becn1,2362.790,2254.330,2451.38,2517.750,2015.56,2558.820,1913.550,2466.440,2379.50,2178.880,2214.350,1955.230
6,1367458_at,Lypla2,672.864,643.214,618.69,572.393,603.48,634.308,597.255,679.507,615.44,679.818,662.065,633.127
7,1367459_at,Arf1,9170.220,9446.720,10982.60,10586.000,9808.95,9583.570,9412.060,11258.800,10112.30,9962.420,9024.520,7830.850
8,1367460_at,Gdi2,5535.990,5477.520,5925.12,6480.930,5420.28,5454.570,5590.680,6059.080,5559.31,5927.780,5240.400,5023.800
9,1367461_at,Copb1,1689.410,1537.770,1590.86,1612.050,1558.45,1666.600,1672.590,1662.830,1493.21,1576.060,1619.280,1414.170

In [50]:
extractor.process_sample_directory()

Processed: GDS3869.soft.gz: Reference Series: GSE23293, PubMed ID: 21270444
Processed: GDS520.soft.gz: Reference Series: GSE854, PubMed ID: 12736351
Processed: GDS1278.soft.gz: Reference Series: GSE3310, PubMed ID: null
Processed: GDS4925.soft.gz: Reference Series: GSE49543, PubMed ID: 24587312
Processed: GDS3182.soft.gz: Reference Series: GSE9103, PubMed ID: null
Processed: GDS5204.soft.gz: Reference Series: GSE53890, PubMed ID: 24670762
Processed: GDS3620.soft.gz: Reference Series: GSE19677, PubMed ID: 20089533
Processed: GDS399.soft.gz: Reference Series: GSE421, PubMed ID: 12902548
Processed: GDS2019.soft.gz: Reference Series: GSE3129, PubMed ID: 19943135
Processed: GDS2929.soft.gz: Reference Series: GSE6591, PubMed ID: 17726092
Processed: GDS1279.soft.gz: Reference Series: GSE3309, PubMed ID: null
Processed: GDS1311.soft.gz: Reference Series: GSE3253, PubMed ID: 15919760
Processed: GDS5217.soft.gz: Reference Series: GSE28392, PubMed ID: 22302958
Processed: GDS288.soft.gz: Reference Series: GSE362, PubMed ID: 12783983
Processed: GDS1803.soft.gz: Reference Series: GSE4332, PubMed ID: 15967997
Processed: GDS2612.soft.gz: Reference Series: GSE6323, PubMed ID: 17381838
Processed: GDS156.soft.gz: Reference Series: GSE80, PubMed ID: 12204100
Processed: GDS5216.soft.gz: Reference Series: GSE25941, PubMed ID: 22302958
Processed: GDS3077.soft.gz: Reference Series: GSE7281, PubMed ID: 17873024
Processed: GDS4904.soft.gz: Reference Series: GSE52550, PubMed ID: 24280126
Processed: GDS2681.soft.gz: Reference Series: GSE4786, PubMed ID: 16890326
Processed: GDS2996.soft.gz: Reference Series: GSE1471, PubMed ID: null
Processed: GDS5412.soft.gz: Reference Series: GSE55162, PubMed ID: 24675804
Processed: GDS2972.soft.gz: Reference Series: GSE8146, PubMed ID: 17316780
Processed: GDS3939.soft.gz: Reference Series: GSE24515, PubMed ID: 21483696
Processed: GDS2639.soft.gz: Reference Series: GSE5666, PubMed ID: 17376971
Processed: GDS1647.soft.gz: Reference Series: GSE3249, PubMed ID: 17012256
Processed: GDS3102.soft.gz: Reference Series: GSE6718, PubMed ID: 17874999
Processed: GDS4874.soft.gz: Reference Series: GSE46646, PubMed ID: 23951254
Processed: GDS2973.soft.gz: Reference Series: GSE8150, PubMed ID: 17316780
Processed: GDS707.soft.gz: Reference Series: GSE1572, PubMed ID: 15190254
Processed: GDS1079.soft.gz: Reference Series: GSE273, PubMed ID: 15569352
Processed: GDS355.soft.gz: Reference Series: GSE459, PubMed ID: null
Processed: GDS4892.soft.gz: Reference Series: GSE50821, PubMed ID: 24797481
Processed: GDS3915.soft.gz: Reference Series: GSE9990, PubMed ID: 19211887
Processed: GDS4522.soft.gz: Reference Series: GSE21935, PubMed ID: 21538462
Processed: GDS5226.soft.gz: Reference Series: GSE25905, PubMed ID: 21545734
Processed: GDS4804.soft.gz: Reference Series: GSE34388, PubMed ID: 22442138
Processed: GDS473.soft.gz: Reference Series: GSE674, PubMed ID: 15036396
Processed: GDS5286.soft.gz: Reference Series: GSE58015, PubMed ID: 25191744
Processed: GDS4264.soft.gz: Reference Series: GSE13122, PubMed ID: 20212020
Processed: GDS40.soft.gz: Reference Series: GSE75, PubMed ID: null
Processed: GDS4019.soft.gz: Reference Series: GSE20219, PubMed ID: 20454453
Processed: GDS287.soft.gz: Reference Series: GSE362, PubMed ID: 12783983
Processed: GDS356.soft.gz: Reference Series: GSE459, PubMed ID: null
Processed: GDS1280.soft.gz: Reference Series: GSE3305, PubMed ID: null
Processed: GDS2082.soft.gz: Reference Series: GSE5078, PubMed ID: 15169854
Processed: GDS4523.soft.gz: Reference Series: GSE17612, PubMed ID: 19255580
Processed: GDS3976.soft.gz: Reference Series: GSE27686, PubMed ID: 21549326
Processed: GDS4858.soft.gz: Reference Series: GSE38718, PubMed ID: 23418191
Processed: GDS2912.soft.gz: Reference Series: GSE3621, PubMed ID: 17696994
Processed: GDS472.soft.gz: Reference Series: GSE674, PubMed ID: 15036396
Processed: GDS5218.soft.gz: Reference Series: GSE28422, PubMed ID: 22302958

Data saved to ../data/pubmed_sample_data.csv

In [53]:
# Load the sample data
data = pd.read_csv("../data/pubmed_sample_data.csv")
data

          File Name Reference Series   PubMed ID
0   GDS3869.soft.gz         GSE23293  21270444.0
1    GDS520.soft.gz           GSE854  12736351.0
2   GDS1278.soft.gz          GSE3310         NaN
3   GDS4925.soft.gz         GSE49543  24587312.0
4   GDS3182.soft.gz          GSE9103         NaN
5   GDS5204.soft.gz         GSE53890  24670762.0
6   GDS3620.soft.gz         GSE19677  20089533.0
7    GDS399.soft.gz           GSE421  12902548.0
8   GDS2019.soft.gz          GSE3129  19943135.0
9   GDS2929.soft.gz          GSE6591  17726092.0
10  GDS1279.soft.gz          GSE3309         NaN
11  GDS1311.soft.gz          GSE3253  15919760.0
12  GDS5217.soft.gz         GSE28392  22302958.0
13   GDS288.soft.gz           GSE362  12783983.0
14  GDS1803.soft.gz          GSE4332  15967997.0
15  GDS2612.soft.gz          GSE6323  17381838.0
16   GDS156.soft.gz            GSE80  12204100.0
17  GDS5216.soft.gz         GSE25941  22302958.0
18  GDS3077.soft.gz          GSE7281  17873024.0
19  GDS4904.soft.gz         GSE52550  24280126.0
20  GDS2681.soft.gz          GSE4786  16890326.0
21  GDS2996.soft.gz          GSE1471         NaN
22  GDS5412.soft.gz         GSE55162  24675804.0
23  GDS2972.soft.gz          GSE8146  17316780.0
24  GDS3939.soft.gz         GSE24515  21483696.0
25  GDS2639.soft.gz          GSE5666  17376971.0
26  GDS1647.soft.gz          GSE3249  17012256.0
27  GDS3102.soft.gz          GSE6718  17874999.0
28  GDS4874.soft.gz         GSE46646  23951254.0
29  GDS2973.soft.gz          GSE8150  17316780.0
30   GDS707.soft.gz          GSE1572  15190254.0
31  GDS1079.soft.gz           GSE273  15569352.0
32   GDS355.soft.gz           GSE459         NaN
33  GDS4892.soft.gz         GSE50821  24797481.0
34  GDS3915.soft.gz          GSE9990  19211887.0
35  GDS4522.soft.gz         GSE21935  21538462.0
36  GDS5226.soft.gz         GSE25905  21545734.0
37  GDS4804.soft.gz         GSE34388  22442138.0
38   GDS473.soft.gz           GSE674  15036396.0
39  GDS5286.soft.gz         GSE58015  25191744.0
40  GDS4264.soft.gz         GSE13122  20212020.0
41    GDS40.soft.gz            GSE75         NaN
42  GDS4019.soft.gz         GSE20219  20454453.0
43   GDS287.soft.gz           GSE362  12783983.0
44   GDS356.soft.gz           GSE459         NaN
45  GDS1280.soft.gz          GSE3305         NaN
46  GDS2082.soft.gz          GSE5078  15169854.0
47  GDS4523.soft.gz         GSE17612  19255580.0
48  GDS3976.soft.gz         GSE27686  21549326.0
49  GDS4858.soft.gz         GSE38718  23418191.0
50  GDS2912.soft.gz          GSE3621  17696994.0
51   GDS472.soft.gz           GSE674  15036396.0
52  GDS5218.soft.gz         GSE28422  22302958.0

In [54]:
data.shape

(53, 3)